### ISSUE TITLE
Cannot connect server which "AllowCorsFrom" config is not empty

### ISSUE THREAD

**Issue by maruTA-bis5** [maruTA-bis5/mattermost-home-timeline-jfx#6]
- App error
```
Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: javax.websocket.DeploymentException: Handshake error.
        at net.bis5.mattermost.hometimeline.service.WebSocketClientService.openConnection(WebSocketClientService.java:101)
        at net.bis5.mattermost.hometimeline.service.WebSocketClientService.lambda$createInitTask$5(WebSocketClientService.java:92)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.websocket.DeploymentException: Handshake error.
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:656)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:694)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:848)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:493)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
        at mattermost4j.websocket@0.12.1-SNAPSHOT/net.bis5.mattermost.websocket.MattermostWebSocketClient.openConnection(MattermostWebSocketClient.java:60)
        at net.bis5.mattermost.hometimeline.service.WebSocketClientService.openConnection(WebSocketClientService.java:98)
        ... 4 more
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 403.
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:299)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:322)
        at tyrus.standalone.client@1.15/org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:291)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at tyrus.standalone.client@1.15/org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        ... 1 more
```

- Server log
```
2019-05-06T08:00:06.440+0900	error	api4/websocket.go:28	websocket connect err: websocket: request origin not allowed by Upgrader.CheckOrigin
2019-05-06T08:00:06.440+0900	error	web/context.go:52	Failed to upgrade websocket connection	{"path": "/api/v4/websocket", "request_id": "yj5gte9kipdd8niqwg5n66djte", "ip_addr": "xxx.xxx.xxx.xxx", "user_id": "", "method": "GET", "err_where": "connect", "http_code": 500, "err_details": ""}
```

**Comment by maruTA-bis5** [comment]
This issue caused by mattermost4j-websocket side.
